# 1. Build Stage
FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# 2. Serve Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
